fail_fast: true
default_install_hook_types: [pre-push]
exclude: |
  (?x)^(
    .*/(snapshots)/.*|
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: docs/cli.md # Exclude generated doc

  - repo: https://github.com/crate-ci/typos
    rev: v1.40.0
    hooks:
      - id: typos

  - repo: local
    hooks:
      - id: foo
        name: foo
        language: system
        entry: sh -c 'sleep 10 && echo hello'
        pass_filenames: false
        priority: 10
      - id: bar
        name: bar
        language: system
        entry: sh -c 'sleep 10 && echo aa >> README.md'
        pass_filenames: false
        priority: 10
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --
        language: system
        types: [rust]
        pass_filenames: false # This makes it a lot faster

      - id: cargo-clippy
        name: cargo clippy
        language: system
        types: [rust]
        pass_filenames: false
        entry: cargo clippy --all-targets --all-features -- -D warnings
