[package]
name = "prek-consts"
version = "0.0.1"
description = "constant values for prek"
repository = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
tracing = { workspace = true }

[lints]
workspace = true
