name: Docker
description: 'Behavior test for Docker Language'

runs:
  using: composite
  steps:
    - name: Setup
      uses: ./.github/actions/setup
    - name: Test Docker
      run: cargo nextest run -- docker::docker --exact --include-ignored
      shell: bash
